# Site settings
title: Gift Hair
email: gomatsuli@yahoo.com
description: > # I make wigs. And specialize in african styles.
  
baseurl: "/gift"
url: "https://dename.github.io"
github_username:  daname

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
